language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: mystera/*
  skip_cleanup: true
  on:
    tags: true